# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
    pull_request:
        types: [closed]
        branches: [public_chxcolate]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run clean
            - run: npm run copy
            - run: npm run replaceDeps
            - run: npm run prettify
            - run: npm run public
              env:
                  email: ${{ secrets.SCREEPS_EMAIL_CHXCOLATE }}
                  password: ${{ secrets.SCREEPS_PASSWORD_CHXCOLATE }}
                  branch: ${{ secrets.SCREEPS_BRANCH_CHXCOLATE }}
